import type { CatalogHotel } from '../../packages/core/src/catalog/types';

/** Synthetic public facts: never availability, real hotel data, DB or provider calls. */
export const hotels: CatalogHotel[] = [
  {
    id: 'demo-malaga',
    name: 'Hotel Demo Málaga',
    country: 'Spain',
    brand: 'aurora',
    guestRating: 4.5,
    reviewCount: 120,
    location: 'Málaga, Spain',
    description: 'Hotel sintético con piscina y aparcamiento publicados.',
    sourceUrl: null,
    highlights: [],
    labels: [],
    image: null,
    attributes: {
      stars: 5,
      destinations: [{ value: 'city/malaga', label: 'Málaga', level: 'city' }],
      services: [
        { value: 'pool', label: 'Piscina', availability: 'available' },
        { value: 'parking', label: 'Aparcamiento', availability: 'available' },
      ],
      themes: [{ value: 'beach', label: 'Playa' }],
      pets: {
        status: 'allowed',
        policyText: 'Se admiten mascotas.',
        sourceUrl: null,
        sourceConflict: false,
      },
      adultsOnly: false,
      provenance: {
        kind: 'synthetic',
        sourceUrl: 'https://example.invalid/catalog-fixture',
        capturedAt: '2026-09-14T00:00:00.000Z',
      },
    },
  },
  {
    id: 'demo-sevilla',
    name: 'Hotel Demo Sevilla',
    country: 'Spain',
    brand: 'mirador',
    guestRating: 4.8,
    reviewCount: 2,
    location: 'Sevilla, Spain',
    description: 'Hotel sintético; aparcamiento sujeto a condiciones.',
    sourceUrl: null,
    highlights: [],
    labels: [],
    image: null,
    attributes: {
      stars: 4,
      destinations: [{ value: 'city/sevilla', label: 'Sevilla', level: 'city' }],
      services: [
        { value: 'pool', label: 'Piscina', availability: 'available' },
        { value: 'parking', label: 'Aparcamiento', availability: 'conditional' },
      ],
      themes: [{ value: 'city', label: 'Ciudad' }],
      pets: {
        status: 'conditional',
        policyText: 'Consultar condiciones.',
        sourceUrl: null,
        sourceConflict: false,
      },
      adultsOnly: false,
      provenance: {
        kind: 'synthetic',
        sourceUrl: 'https://example.invalid/catalog-fixture',
        capturedAt: '2026-09-14T00:00:00.000Z',
      },
    },
  },
  {
    id: 'demo-lisboa',
    name: 'Hotel Demo Lisboa',
    country: 'Portugal',
    brand: 'aurora',
    guestRating: null,
    reviewCount: null,
    location: 'Lisboa, Portugal',
    description: 'Hotel sintético sin valoración ni política de mascotas confirmadas.',
    sourceUrl: null,
    highlights: [],
    labels: [],
    image: null,
  },
];
